import 'dotenv/config';
import { Agent, run} from "@openai/agents";
import { z } from "zod";
import axios from "axios";  

const sqlGuardrailAgent = new Agent({
    name:'SQL query guardrail agent',
    instructions:`You are an expert agent that checks if the SQL query generated by the SQL expert agent is safe to execute or not.
    The query should be read-only and do not modifym,delete or insert any data in the database.
    `,
    outputType: z.object({
        isSafeQuery: z.boolean().describe("Whether the SQL query is safe to execute or not"),
        reason: z.string().optional().describe("The reason why the SQL query is or isn't safe to execute"),
    }),
});

const sqlOutputGuardrail = {
    name : "sql_output_guardrail",
    async execute ({agentOutput}) {
        const result = await run(sqlGuardrailAgent, agentOutput.sqlQuery);
       return {
        outputInfo: result.finalOutput.reason || "No reason provided",
        tripwireTriggered: result.finalOutput.isSafeQuery?false:true,
       }
    },
};
        

const sqlAgent = new Agent({
    name:'SQL expert agent',
    instructions:`you are and expert agent in generating SQL queries as per user request.
    postgres Schema:
Table: employees
Columns:
- id (integer, primary key)
    `,
    outputType: z.object({
        sqlQuery: z.string().optional().describe("The SQL query generated as per user request"),
    }),
    outputGuardrails: [sqlOutputGuardrail],
});


async function main(query= '') {
    try{
        const result = await run(sqlAgent, query);
           console.log('Result:',result.finalOutput.sqlQuery);
           // console.log('Result:',result.history);
    } catch (error) {
            console.error('Error:', error);
    }
}

main('delete all the employees'); // This should pass the guardrail